# -*- coding: utf-8 -*-
"""生成调研报告终稿（表格由台账程序化生成）"""
import json, os, csv
BASE=r"E:\RESEARCH\agentic\docs\research"
DATA=os.path.join(BASE,"data")
rows=list(csv.DictReader(open(os.path.join(DATA,"ledger.csv"),encoding="utf-8-sig")))
for r in rows:
    r["_s"]=int(r["stars"]); r["_d"]=int(r["days_since_last_push"]) if r["days_since_last_push"]!="" else 999
BY={r["full_name"]:r for r in rows}
def fnum(x):
    try: return f"{int(x):,}"
    except: return "—"
def act(d):
    if d<=3: return "活跃"
    if d<=30: return "较活跃"
    if d<=120: return "放缓"
    return "停滞"

top=sorted(rows,key=lambda r:-r["_s"])[:20]
T=["| # | 项目 | 分类 | Stars | Forks | 主语言 | 许可证 | 创建 | 最近推送 | 活跃度 |","|---|------|------|------:|------:|--------|--------|------|----------|--------|"]
for i,r in enumerate(top,1):
    T.append(f"| {i} | [{r['full_name']}]({r['html_url']}) | {r['group']} | {fnum(r['_s'])} | {fnum(r['forks'])} | {r['language'] or '—'} | {r['license'] or '—'} | {r['created_at']} | {r['pushed_at']} | {act(r['_d'])} |")
TOP20="\n".join(T)

FLAG1=[
("langchain-ai/langgraph","图式状态编排框架：把 agent 流程建模为可持久化的图，主打生产级状态/回滚/人机协同","有状态、可恢复的生产级 agent","高"),
("openai/openai-agents-python","轻量多智能体 SDK：handoffs 交接 + 内置 tracing，OpenAI 官方","快速构建多 agent 工作流（OpenAI 生态）","低-中"),
("google/adk-python","代码优先 agent 工具包：多模型、可评估、可观测，Google 官方","GCP/多模型生产 agent","中"),
("pydantic/pydantic-ai","类型安全结构化 agent 框架：以 Pydantic 校验为核心","需要严格结构化输出的 agent","中"),
("huggingface/smolagents","极简 code-first agent：让模型自己写代码调用工具","教学/快速原型/轻量部署","低"),
("microsoft/semantic-kernel","企业级跨语言（C#/Py/Java）agent 框架",".NET/企业现有技术栈集成","中-高"),
("crewAIInc/crewAI","角色化多智能体编排：定义角色/任务/流程，低代码心智","角色团队式业务自动化（MVP 快）","低"),
("microsoft/autogen","对话式多智能体框架（已进入维护模式）","研究/多 agent 对话（迁移中）","中"),
("bytedance/deer-flow","长程 SuperAgent harness：面向小时级研究/编码/创作任务","复杂长程任务自动化","中"),
("mastra-ai/mastra","TypeScript 全栈 agent 框架：workflows/agents/工具一体","TS 技术栈的 agent 应用","中"),
("obra/superpowers","Agentic Skills 框架+开发方法论：以 skills/子代理驱动开发","给编码 agent 注入可复用技能栈","低"),
("affaan-m/ECC","Agent harness 性能优化系统：skills/instincts/memory","让 Claude Code/Codex 更快更稳更省 token","中"),
]
FLAG2=[
("openclaw/openclaw","全平台个人 AI 助理（Own-Your-Data），2025-11 创建即登顶","个人日常/跨设备自动化","低"),
("anthropics/claude-code","官方终端编码 agent","CLI 内完成编码任务","低"),
("openai/codex","官方终端编码 agent（Rust）","CLI 内完成编码任务","低"),
("google-gemini/gemini-cli","官方终端编码 agent","CLI 内完成编码任务","低"),
("anomalyco/opencode","开源终端编码 agent（opencode 继任仓库）","自托管/可定制 CLI","中"),
("OpenHands/OpenHands","自主软件工程平台：Agent Canvas 自托管 agent 工程团队","自动化开发任务/工程团队","中"),
("browser-use/browser-use","让 AI 操作浏览器的开源库（高动量）","网页自动化/数据采集/测试","中"),
("langgenius/dify","可视化 LLM 应用开发平台","业务团队快速搭 agent 应用","低"),
("n8n-io/n8n","工作流自动化平台（含 agent 节点与 MCP）","集成/自动化（200k★ 平台）","低-中"),
("langflow-ai/langflow","可视化 agent 构建（Python 后端）","可视化多 agent 工作流","低"),
("open-webui/open-webui","自托管 AI 界面（多模型/MCP）","团队私有 AI 门户","低"),
("modelcontextprotocol/servers","MCP 官方参考服务器实现","为 agent 提供工具/数据连接","中"),
("a2aproject/A2A","Agent2Agent 开放协议","跨厂商 agent 互操作","中"),
("mem0ai/mem0","Agent 记忆层（跨框架 SDK）","个性化/长期记忆","中"),
("ComposioHQ/composio","Agent 工具/集成层（1000+ 工具，MCP 远程服务器）","工具接入与认证","中"),
("firecrawl/firecrawl","网页上下文 API（搜索/抓取/转 Markdown）","agent 的联网数据底座","中"),
]
def flag_table(fl):
    L=["| 项目 | 定位/心智模型 | 主语言 | 许可 | Stars (08-11) | 最近推送 | 典型场景 | 上手难度 |","|---|---|---|---|---:|---|---|---|"]
    for full,pos,scene,diff in fl:
        r=BY.get(full)
        if not r: continue
        L.append(f"| [{full}]({r['html_url']}) | {pos} | {r['language'] or '—'} | {r['license'] or '—'} | {fnum(r['_s'])} | {r['pushed_at']} | {scene} | {diff} |")
    return "\n".join(L)

R=[]
R+=["# GitHub 热门 AI Agent 项目调研报告：比较分析与分类总结","",
"> **任务 TK-013 · Agentic Co-Lab 研究院 · 2026-08-11 · 版本 v1.0**","",
"> **数据时点**：2026-08-11T10:22:39+00:00（UTC）GitHub REST API 快照（采集窗口约 40–50 分钟，个别补充项目稍晚，见台账 `source` 列）",
"> **样本**：60 个项目 · **来源**：GitHub 官方 API（`/repos` + `/search/repositories`）· 三层核验（双端点交叉 + ai-agent-pulse 同日 + 第三方榜单/报道）",
"> **配套文档**：数据采集台账｜数据核验记录｜方案与执行说明（见 `docs/research/README.md`）","",
"---","",
"## 执行摘要","",
"1. **生态主导权已交接**：2026 年 8 月的热度榜头部分别是 2025–2026 年创建的**成品 Agent 与技能层**项目——`openclaw/openclaw`（385,885★，全 GitHub 软件项目第一）、`obra/superpowers`（270,517★）、`affaan-m/ECC`（239,335★）、`NousResearch/hermes-agent`（228,737★）；而 2023 年的先驱（AutoGPT、MetaGPT、AutoGen、Swarm）star 存量仍高，但**活跃度明显下滑或进入维护模式**（MetaGPT 202 天、AutoGen/Swarm 117 天未推送；AutoGen 10 个月未发版、4 周 0 提交）。",
"2. **三大模型厂商的终端 CLI 正面交锋**：Claude Code（141,016★）、Codex（105,274★）、Gemini CLI（106,457★）均为 2025 年发布、一年内冲上 10 万+；开源编码 agent 矩阵（OpenHands、OpenCode、Cline、Aider、Goose、Continue、pi）同步繁荣。",
"3. **新品类爆发：Agent 技能/增强层**。以 CLAUDE.md/skills/插件为分发单元的技能框架（superpowers、ECC、hermes-agent、claude-mem）增速超过多数传统框架——用户痛点正从「学新框架」转向「让现有 agent 更好用」。",
"4. **多智能体编排进入洗牌期**：AutoGen 官方迁移至 Microsoft Agent Framework/AG2；CrewAI（角色化，7 日 +328★）与 LangGraph（图+持久化，7 日 +589★）成为两条主流路线；deer-flow（79,727★）代表「长程任务 SuperAgent」新方向。",
"5. **基础设施协议化**：MCP 成为事实标准（官方实现 89,427★，社区榜单 9.2 万★），A2A（25,284★）指向 agent↔agent 互操作；记忆（mem0/Letta/claude-mem）、工具（Composio）、数据（Firecrawl/RAGFlow）各自成赛道。",
"6. **选型警示**：star 是「历史品牌 + 当下热度」的混合信号，与工程活跃度可能背离（AutoGPT、MetaGPT、AutoGen 即例证）。本报告同时给出 star、活跃度、第三方动量三层证据。","",
"---","",
"## 一、调研范围与方法（摘要）","",
"- **样本**：60 个代表性项目，选取流程 = 领域预选（42）→ GitHub search API 客观检索补漏（topic:ai-agents 等 5 组 Top30）→ 第三方榜单交叉（ai-agent-pulse 19 框架、Agent-Leaderboard 5 板块）→ 增补与更正（含 openclaw、opencode 继任等）。",
"- **度量**：star 数（规模/热度）、forks/watchers（社区参与）、最近推送日期（活跃度代理）、创建日期（代际）、许可证（合规前提）；第三方 7 日 star 增量与 4 周提交（动量）。",
"- **核验**：23 个项目双端点交叉（差异 ≤1）；ai-agent-pulse（同日）19 框架量级全部一致；公开报道趋势一致。详见《数据核验记录》。",
"- **诚实边界**：单时点快照；star 每分钟波动 ±1；部分项目因配额由 search API 采集（同源官方，已标注）；「活跃度」以最近推送为代理；分类按首要定位存在交叉；未评估代码质量/安全。","",
"---","",
"## 二、全景概览","",
"### 2.1 Top 20（数据时点 2026-08-11T10:22:39Z）","",
TOP20,"",
"### 2.2 量级与结构","",
"- 60 个项目 star 合计约 **466 万**，中位数 55,316；≥10 万★ 15 个，5–10 万★ 17 个，2–5 万★ 18 个。",
"- 主语言：**Python 31**、TypeScript 17、Shell 3、JavaScript 2、Rust 2、Go 2、C# 1、Swift 1——Python 在 agent 开发层占绝对主导，TypeScript 在平台/应用层强势。",
"- 许可证：MIT 22、Apache-2.0 20、**NOASSERTION（自定义/未识别）11**、无许可证 3、AGPL-3.0 2、CC-BY-4.0 1——**约 1/4 头部项目许可证非标准**（如 openclaw、n8n、dify、AutoGPT、Open WebUI 等），商用选型需单独核验条款。",
"- 活跃度（截至快照）：48 个 ≤3 天内推送；4–30 天 5 个；31–120 天 3 个（aider、autogen、swarm）；>120 天 3 个（MetaGPT 202 天、autoresearch 138 天、opencode-ai 327 天且已归档）。",
"- 交叉能力：13 个项目 topics 明示 **MCP** 支持（n8n、dify、Open WebUI、LobeHub、Goose、Composio、AgentScope、Mastra、Haystack、AG2 等），12 个项目明示 **multi-agent** 定位。","",
"---","",
"## 三、分类体系","",
"### 3.1 分类逻辑","",
"分类以「**交付形态 × 使用对象**」为第一性原则（用户拿到手的是什么、由谁使用），辅以「解决什么问题」。共 7 类：","",
"| 类 | 交付形态 | 使用对象 | 代表项目 |",
"|---|---|---|---|",
"| ① 框架与开发库（18） | 编程 API/SDK | 开发者 | LangGraph、OpenAI Agents SDK、ADK、PydanticAI、Smolagents、Semantic Kernel、LlamaIndex、Mastra、Haystack、Agent Framework、Agno、Nanobot 等 |",
"| ② 多智能体编排（10） | 多 agent 协作框架/应用 | 开发者/业务方 | CrewAI、AutoGen/AG2、MetaGPT、CAMEL、AgentScope、Swarm、deer-flow、Agent Squad、TradingAgents |",
"| ③ Agent 应用·编码（15） | 成品编码 agent | 开发者（终端用户） | Claude Code、Codex、Gemini CLI、OpenCode、OpenHands、AutoGPT、Cline、Aider、Continue、Goose、pi、browser-use、Skyvern、Eliza |",
"| ④ Agent 应用·个人/研究（2） | 成品个人助理/研究 agent | 个人用户 | OpenClaw、autoresearch |",
"| ⑤ Agent 平台/低代码（6） | 可视化平台 | 业务/半技术人员 | n8n、Langflow、Dify、Open WebUI、LobeHub、Flowise |",
"| ⑥ 协议/基础设施/记忆（10） | 协议、服务、SDK 组件 | 开发者/所有层 | MCP (spec+servers)、A2A、mem0、Letta、claude-mem、Composio、Firecrawl、RAGFlow |",
"| ⑦ Agent 技能/增强层（并入①③相关分析） | 技能包/配置/方法论 | 开发者（增强现有 agent） | superpowers、ECC、hermes-agent |",
"","**边界处理**：LangGraph 既可单 agent 也可多 agent，按「首要定位=框架」归①；TradingAgents 是金融多 agent **应用**，归②并在文中注明；superpowers/ECC 严格说是「增强层」而非框架，归①并在 4.6 单独分析；Eliza 是社交/链上 agent 应用，归③。分类有主观成分，已在台账 `group` 列完整标注，便于读者按自己口径重排。","",
"### 3.2 生态结构图景（文字版）","",
"```text",
"                    应用层（终端用户直接用）",
"   编码 CLI/IDE      |   浏览器/网页   |   个人助理/研究",
"  Claude Code Codex  | browser-use     | OpenClaw(38.6万)",
"  Gemini CLI OpenCode| Skyvern         | hermes-agent(22.9万)",
"  OpenHands Cline    |                 | autoresearch",
"  Aider Goose pi     |                 |",
" -----------------------------------------------------------------",
"      平台/低代码层（业务用户）        技能/增强层（开发者）",
"  n8n(20万) Langflow Dify            superpowers(27万)",
"  Open WebUI LobeHub Flowise         ECC(23.9万) claude-mem",
" -----------------------------------------------------------------",
"      框架与开发库层（开发者）        多智能体编排层",
"  LangGraph OpenAI SDK ADK          CrewAI AutoGen/AG2",
"  PydanticAI Smolagents SK          MetaGPT CAMEL AgentScope",
"  LlamaIndex Mastra Haystack        deer-flow Swarm",
" -----------------------------------------------------------------",
"      基础设施/协议层（所有层共享）",
"  MCP(spec+servers 9.8万) A2A(2.5万) mem0 Letta Composio",
"  Firecrawl(16.5万) RAGFlow(8.7万)",
"```","",
"---","",
"## 四、分领域分析","",
"### 4.1 框架与开发库（18 个）——「图编排 vs 轻量 vs 结构化」三分","",
"- **生产级图编排**：LangGraph 以「图 + 持久化 + 人机协同」成为生产标杆（Pulse 75.3，7 日 +589★）；LangChain 作为其父生态（143,963★）仍是最大入口。",
"- **官方轻量 SDK**：OpenAI Agents SDK（28,555★，handoffs）、Google ADK（21,069★）、Claude Agent SDK（1,688★，SDK 本体小但 CLI 141k）——模型厂商通过 SDK 锁定开发者心智。",
"- **结构化/极简**：PydanticAI（19,219★）以类型安全为卖点；Smolagents（28,751★）极简 code-agent（但 2 个月未发版、4 周 0 提交，Pulse 37.7 偏低）；Semantic Kernel（28,439★）服务企业现有技术栈（C#/Java）。",
"- **TS 全栈**：Mastra（27,097★，4 周 1292 提交，开发最活跃）、Vercel AI SDK（26,125★）服务前端/全栈场景；Microsoft Agent Framework（12,727★）是 AutoGen 的官方继任。",
"- **洞察**：框架层没有统一赢家——「状态与生产」「类型安全」「极简」「厂商绑定」「前端接入」各占位；选型取决于**已有技术栈 + 是否需要持久化状态**。","",
"### 4.2 多智能体编排（10 个）——从「对话」走向「生产与长程」","",
"| 项目 | Stars | 心智模型 | 活跃信号（2026-08） | 定位判断 |",
"|---|---:|---|---|---|",
"| crewAIInc/crewAI | 56,931 | 角色/任务流程 | 7d +328，Pulse 77.7，2 天前发版 | 角色化编排，上手快，动量高 |",
"| microsoft/autogen | 60,356 | 多 agent 对话 | 117 天未推送，10 个月未发版，4 周 0 提交 | 维护模式；官方推荐迁移至 Agent Framework/AG2 |",
"| ag2ai/ag2 | 4,851 | AutoGen 社区分支 | 13 天前发版，活跃度有限 | 小众续命分支 |",
"| FoundationAgents/MetaGPT | 69,770 | 「AI 软件公司」流水线 | **202 天未推送** | 理念先驱，工程停滞 |",
"| bytedance/deer-flow | 79,727 | 长程 SuperAgent | 2025-05 创建，活跃 | 新星：长程研究/编码/创作 |",
"| camel-ai/camel | 17,572 | 角色扮演+研究 | 4 天前推送 | 研究向 |",
"| agentscope-ai/agentscope | 28,817 | 可视化可观测多 agent | 活跃，MCP 支持 | 阿里系，可观测性卖点 |",
"| openai/swarm | 21,893 | 教学/实验 | 117 天未推送 | 官方定位教学，基本停滞 |",
"| 2FastLabs/agent-squad | 7,734 | AWS 多 agent 编排 | 1 天前推送 | 云厂商入局 |",
"| TauricResearch/TradingAgents | 97,490 | 多 agent 金融交易 | 23 天前推送 | 领域应用型 |",
"",
"**洞察**：多智能体正在经历「演示→生产」的筛选——只有解决**状态持久、可观测、可控**问题的框架（LangGraph/CrewAI/deer-flow 路线）获得动能；纯对话式（Swarm）与流水线式（MetaGPT）回落。",
"",
"### 4.3 编码与通用 Agent 应用（15+2 个）——终端入口争夺战","",
"- **官方 CLI 三巨头**（均为 2025 年发布、1 年内 10 万+）：Claude Code 141,016 / Gemini CLI 106,457 / Codex 105,274——终端成为模型厂商的直接入口。",
"- **开源编码矩阵**：OpenCode（继任仓库 196,028★，Go）、OpenHands（83,691★，自主工程平台）、pi（87,258★）、Cline（65,991★，IDE 插件）、Goose（52,669★，Rust）、Aider（48,116★，git 原生，80 天未推送）、Continue（35,430★，IDE）、Skyvern（22,730★，网页自动化）、browser-use（108,742★，浏览器库，7 日 +904★，Pulse 89.2 全场第一）。",
"- **个人助理/研究**：OpenClaw（385,885★，2025-11 创建，全平台个人 AI 助理，登顶 GitHub 总榜）；autoresearch（93,644★，Karpathy 的实验性研究 agent，138 天未推送，属实验项目）。",
"- **洞察**：编码 agent 是当前最成熟、竞争最激烈的赛道；「官方 CLI + 开源替代 + 浏览器自动化」构成三层，其中**浏览器自动化（browser-use）是当前动量最高的细分**。",
"",
"### 4.4 平台/低代码（6 个）——业务侧需求旺盛","",
"- n8n（200,194★，含 agent 节点与 MCP，工作流自动化老牌平台）、Langflow（153,046★，可视化 agent 构建）、Dify（152,076★，LLM 应用平台，自 2026-01 破 10 万后高速增长）、Open WebUI（148,456★，自托管门户）、LobeHub（81,492★）、Flowise（55,316★）。",
"- **洞察**：平台层与框架层互补而非替代——**业务用户用平台（低代码），开发者用框架（代码）**；六家平台 star 合计约 79 万，证明「无代码搭 agent」是真实刚需。",
"",
"### 4.5 协议/基础设施/记忆（10 个）——生态的「水电煤」","",
"- **协议**：MCP（spec 8,921 + servers 89,427★）已成为 agent 工具连接的事实标准（社区 awesome-mcp-servers 9.2 万★、chrome-devtools-mcp 4.9 万★、github-mcp-server 3 万★为佐证）；A2A（25,284★，Google 主导）指向 agent↔agent 互操作。",
"- **记忆**：mem0（63,014★）、claude-mem（90,376★，技能型记忆）、Letta（24,186★）。",
"- **工具/数据**：Composio（29,627★，1000+ 工具与远程 MCP 服务器）、Firecrawl（165,519★，网页上下文 API）、RAGFlow（87,248★，RAG 引擎）。",
"- **洞察**：agent 数量爆发后，瓶颈从「能不能生成」转向「连得上工具、记得住上下文、拿得到数据」——基础设施层是 2026 年确定性最强的增长方向。",
"",
"### 4.6 Agent 技能/增强层（新品类，2025-10 后爆发）","",
"- superpowers（270,517★，2025-10 创建）：Agentic Skills 框架 + 开发方法论，以「技能包」形式注入编码 agent；",
"- ECC（239,335★，2026-01 创建）：Agent harness 性能优化（skills/instincts/memory），目标是让 Claude Code/Codex 更快、更省 token；",
"- hermes-agent（228,737★，2025-07 创建）：「成长型 agent」，技能随使用增长；",
"- claude-mem（90,376★）：跨会话持久记忆。",
"- **洞察**：这类项目不替代框架，而是**增强现有 agent**——其 star 增速（半年 20–30 万）远超多数框架，标志 2026 年的核心矛盾是「现有 agent 不够好用」而非「没有新框架」。",
"",
"---","",
"## 五、关键维度横向对比","",
"下表为旗舰项目对比；「定位/心智模型、典型场景、上手难度」为**定性判断**（基于项目官方描述与通用认知，非本次 API 核验项）；「语言/许可/Stars/最近推送」为本调研 API 实测（2026-08-11）。","",
"### 5.1 开发层（框架/多智能体/技能层）","",
flag_table(FLAG1),"",
"### 5.2 应用与平台/基础设施","",
flag_table(FLAG2),"",
"---","",
"## 六、洞察与结论（数据驱动）","",
"1. **时代切换：从「框架」到「成品 Agent + 技能层」**。Top10 中 7 个创建于 2024-10 之后；2023 先驱（AutoGPT/MetaGPT/AutoGen）活跃度全面回落（MetaGPT 202 天、AutoGen 117 天）。**star 存量是历史品牌，活跃度才是当下动能。**",
"2. **模型厂商的「入口战争」集中在终端 CLI**：Anthropic/OpenAI/Google 三家官方 CLI 一年内全部破 10 万★。终端是比 IDE 更轻、更可控的 agent 入口；开源替代（OpenCode 196k/OpenHands 84k）以「可自托管、模型无关」差异化。",
"3. **技能/增强层是 2026 年最大新品类**：superpowers/ECC/hermes-agent 合计约 74 万★，均诞生于最近 10 个月。分发单元从「框架」变成「可移植技能包」，跨 Claude Code/Codex/Gemini CLI/Cursor 复用。",
"4. **多智能体从演示走向生产，胜者是「可控」**：CrewAI（角色化，+328/7d）、LangGraph（图+持久化，+589/7d）、deer-flow（长程 harness，79.7k★）获得动能；Swarm 停滞、AutoGen 维护模式。**「多」不是卖点，「可恢复、可观测、可编排」才是。**",
"5. **MCP 完成事实标准化，A2A 开辟第二协议**：MCP 生态（官方实现 + 社区榜单 9 万+）已渗透到平台（n8n/dify/Open WebUI）、框架（AgentScope/Mastra/Haystack）与工具层（Composio）。跨厂商 agent 互操作（A2A）是下一个待垦地。",
"6. **Python 主导开发层、TypeScript 崛起于应用/平台层**：31/60 为 Python；但 OpenClaw、n8n、Dify、Open WebUI、LobeHub、Mastra、Composio、Firecrawl 等头部应用/平台均为 TS。",
"7. **中文/中国团队深度参与**：deer-flow（字节）、AgentScope（阿里）、RAGFlow、MetaGPT 及大量中文技能/教程/榜单仓库——本生态已高度全球化，中文本地化内容供给活跃。",
"8. **选型三问**：① 看活跃度与发版（而非只看 star，AutoGPT/MetaGPT/AutoGen 为反例）；② 核对许可证（60 个样本中 14 个为非标准/无许可证）；③ 明确「代码 vs 低代码」「框架 vs 成品」「单机 vs 托管」三条轴后再选。",
"",
"---","",
"## 七、风险与局限（诚实标注）","",
"1. **单时点快照**：数据为 2026-08-11T10:22:39Z 前后约 40–50 分钟内采集；star 每分钟波动 ±1（双端点复核实测）。",
"2. **配额降级**：17 个补充项目因核心 API 60 次/小时配额限制改用 search API（GitHub 官方同源），台账 `source` 列逐一标注；不影响真实性，但严格意义上部分项目未走主端点。",
"3. **活跃度代理**：「最近推送」不反映提交频率/PR/Issue 全貌；已用 ai-agent-pulse 的 4 周提交与 7 日增量交叉，但该第三方自身为自动化快照，可能有数小时到数天滞后。",
"4. **star ≠ 质量**：未评估代码质量、文档、安全、生产可用性；部分头部项目（如 OpenClaw 38.6 万★）创建不足 1 年，成熟度待观察；公开报道亦提示个人 Agent 存在安全风险。",
"5. **分类主观性**：按「交付形态 × 使用对象」分类存在天然交叉（LangGraph 等），已提供台账全量分组供读者重排。",
"6. **未覆盖项**：非开源/闭源产品（Devin、Manus、Cursor、Coze 等）与纯列表/教程类仓库未入主样本（见「附：生态邻接」）；star-history.com 因 GitHub 限制不可用，未获得逐日增长曲线。",
"7. **时效性**：AI agent 领域变化以周计；本报告结论截至数据时点，头部格局可能快速变化（如 openclaw 2025-11 创建后 9 个月登顶即是例证）。","",
"## 附：生态邻接（未入主样本但值得关注）","",
"- 纯列表/教程：awesome-llm-apps（132k）、system-prompts-and-models-of-ai-tools（143k）、ai-agent-book（36k）、agents-towards-production、GenAI_Agents、awesome-cursorrules、ComposioHQ/awesome-claude-skills（72k）。",
"- 非开源产品：Devin、Manus、Cursor、Windsurf、Coze/扣子、Copilot。",
"- 相邻基础设施：vLLM、LLaMA-Factory（推理/训练）、DSPy（37k，prompt 优化）、RAGFlow（已入样本）、Langfuse（可观测）。",
"- MCP 生态：awesome-mcp-servers（92k）、chrome-devtools-mcp（49k）、github-mcp-server（30k）、playwright-mcp（33k）。",
"",
"---","",
"*本报告所有数字可回溯至 `data/ledger.csv`、`data/raw/`（原始 JSON）与《数据核验记录》。复现方式见《方案与执行说明》与 `process/collect_github_data.py`。*",""]
open(os.path.join(BASE,"2026-08-11-AI-Agent生态调研-调研报告.md"),"w",encoding="utf-8").write("\n".join(R))
print("report written, chars=", sum(len(x) for x in R))
